### ISSUE TITLE
Freezes the browser tab.

### ISSUE THREAD

**Issue by SrLicht** [cherninlab/breek#1] opened 2024-09-14 08:04 UTC
When trying to load the game the tab will freeze and will not respond.

**Comment by cherninlab** [comment] 2024-09-16 11:46
Thanks for reporting this
I'll update this thread once I have more information or a fix.

**Comment by cherninlab** [comment] 2024-09-23 19:37
The freezing issue is likely caused by the game's heavy reliance on SVG SMIL animations. I will update this thread as soon as the fix is implemented.

**Comment by cherninlab** [comment] 2024-11-17 23:24
The issue has been fixed in version 1.0.5 by replacing SVG SMIL animations with CSS animations.
The fix is now in production and can be seen in the `/packages/svg-creator/src/index.ts`
Closing this issue as resolved. 👍

**Closed as completed by cherninlab** 2024-11-17 23:24 UTC
Labels: bug
